### ISSUE TITLE
GCC port of NVEL

### ISSUE THREAD

**Issue by Crghilardi** [tharen/pynvel#1]
Hello, 

this is a bit tangential, but I have been experimenting with the NVEL library myself and have started writing a gfortran port with a makefile since I don't have access to the Intel compiler that the batch files in the FMSC repo use. I have been in email contact with YingFang at the FMSC and have sent it to him as well. 

Is there any interest/value in that code for this project? I noticed that the fork this repo reference has some work with CMake already added in. It would be nice to contribute and hopefully alleviate possible duplicate work.

Thank you

**Comment by tharen** [comment]
Note that the NVEL code currently compiles with GFortran as is. The CMakeLists.txt file adds the appropriate flags. I use the Windows compilers from the MinGW-w64 project. I have not tested this setup in Linux yet.

My fork of the NVEL code is currently unmodified except for the addition of the [CMakeLists.txt](https://github.com/tharen/VolumeLibrary/blob/master/CMakeLists.txt) file. This works well for generating the Python extension, but I have not tested it with other languages, R, C#, VB, etc.

If you have modifications for other platforms and languages that could be helpful. Also, be aware that some compiler flag combinations affect the floating point arithmetic results. I have not thoroughly tested these differences. There are a few simple unit tests, but they are for a small subset of the volume equations.

**Comment by Crghilardi** [comment]
OK, I will work on submitting a pull request to the tharen/VolumeLibrary fork. I do not have much experience with compiled languages, so I am unsure of its implementation merit relative to your work.

I am using MinGW64 on Windows 10 only. My work was mainly trying to add some directory structure to make it easier to read and direct output objects/dll and I figured there would be some added benefit to matching the tooling of open-FVS.

**Comment by tharen** [comment]
I too struggle with the compiled languages. Mostly from the standpoint of integrating them with other high level languages. Issues with data types, structures, calling conventions, etc. can be a pain.

I've mostly focussed on writing wrappers using the existing code. I used to try and modify the project structure and integrate it more with my code. I found it difficult to keep track of changes and eventually chose to keep them separate when possible. With CMake, etc. it's straight forward to kick out an object library that GCC/GFortran can then link to statically, or a DLL.

With regard to Open-FVS I'll probably take a similar approach with [PyFVS]. Right now I've incorporated the FVS code directly and heavily modified portions of it to bring up to Fortran 90, using modules, etc. But this makes it cumbersome to integrate upstream changes.

In time it would be nice to see the NVEL library as a submodule linked into FVS. Since FVS used the NVEL code this shouldn't be difficult. I haven't had time to attempt this myself, but I think it'd be a good step towards demonstrating a more modular project structure.

**Comment by Crghilardi** [comment]
[Pull request submitted here](https://github.com/tharen/VolumeLibrary/pull/1). I tried for a short while to understand the interplay between the NVEL and the volume routines [nested in FVS](https://sourceforge.net/p/open-fvs/code/HEAD/tree/trunk/volume/) but I couldn't make sense of it and discrepancies between files.
